name: Release to Develop Environment
on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOY_PATH }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/server_id/mydomein.jp/sample/
            git checkout develop
            git pull origin develop